name: Docker Build and Push

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'packages/server/**'
      - '.github/workflows/build-push.yml'
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Image Tag
        run: |
          if [ "$GITHUB_REF" = "master" ]; then
            echo "BRANCH_NAME=latest" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          IMAGE_NAME=michaelfrancisco/chat_server:$BRANCH_NAME
          docker build -t $IMAGE_NAME -f packages/server/Dockerfile .
          docker push $IMAGE_NAME