name: Docker Build and Push

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'packages/server/**'
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          TAG=${GITHUB_REF/refs\/heads\//}
          make build-and-push TAG=${TAG}